Add documentation to the `dot` command

diff --git a/bin/dot b/bin/dot
--- a/bin/dot
+++ b/bin/dot
@@ -1,15 +1,17 @@
 #!/usr/bin/env bash
 
-set -euo pipefail
+set -eo pipefail
 
 source "$DOTLY_PATH/scripts/core/_main.sh"
 
 ##? Usage:
 ##?    dot
 ##?    dot <context>
-##?    dot <context> <cmd> [<args>...]
-##?    dot -h <context> <cmd>
-docs::parse
+##?    dot <context> <script> [<args>...]
+##?    dot -h | --help
+if [ "$1" == "-h" ] || [ "$1" = "--help" ]; then
+  docs::parse "$@"
+fi
 
 exit_if_empty() {
   [ "${1}" == "" ] && die "No executable scripts" || true
@@ -21,7 +23,7 @@ fzf_prompt() {
 
   match="$(echo "$paths" |
     xargs -I % sh -c 'echo "$(basename $(dirname %)) $(basename %)"' |
-    fzf --height 100% --preview '$DOTLY_PATH/bin/dot -h $(echo {} | cut -d" " -f 1) $(echo {} | cut -d" " -f 2)')"
+    fzf --height 100% --preview '$DOTLY_PATH/bin/dot $(echo {} | cut -d" " -f 1) $(echo {} | cut -d" " -f 2) -h')"
   printf "$match"
   read args
   if coll::is_empty "$args"; then
@@ -39,7 +41,7 @@ ask_for_help() {
   [ "${1}" == "true" ]
 }
 
-generate_help () {
+generate_help() {
   "${1}/scripts/${2}/${3}" -h
 }
 
@@ -47,11 +49,12 @@ help="false"
 while getopts ":h" opt; do
   shift 1
   case $opt in
-    h) help="true"
+  h)
+    help="true"
     ;;
-    [?])
-      echo "Invalid option -$opt" >&2
-      exit 1
+  [?])
+    echo "Invalid option -$opt" >&2
+    exit 1
     ;;
   esac
 done
