Final edit version

diff --git a/scripts/symlinks/edit b/scripts/symlinks/edit
--- a/scripts/symlinks/edit
+++ b/scripts/symlinks/edit
@@ -43,42 +43,68 @@ if ${version:-}; then
   exit
 fi
 
+output::empty_line
+
 yaml_file="$(symlinks::get_file_path "$yaml_file")"
+[[ -z "${yaml_file:-}" ]] && output::error "The dotbot yaml file '$yaml_file' does not exists." && exit 1
 
-links=("${origin_link_path:-}")
-new_links=("${new_origin_link_path:-}")
 
-preview_cmd='. "$DOTLY_PATH/scripts/core/_main.sh";'
-preview_cmd+='dot::get_script_src_path "dotbot_yaml_edit.sh";'
-preview_cmd+="yaml_file=$yaml_file;"
-preview_cmd+='echo "Press Tab+Shift to select multiple options.\n'
-preview_cmd+='Press Ctrl+C to exit with no selection.\n\n'
-preview_cmd+='----\n\nLinks:\n\n'
-preview_cmd+='$(cat "$yaml_file" | dotbot::jq_yaml_file -r ".[].link | values")";'
+if [[ -n "${origin_link_path:-}" ]]; then
+  yaml_link_value="$(dotbot::get_value_of_key_in "link" "$origin_link_path" "$yaml_file")"
+  [[ -z "${yaml_link_value:-}" ]] && output::error "Given link does not exists so it is no possible to edit." && exit 1
 
-if [ -z "${links[*]}" ] && $by_value; then
-  dotfiles=($(dotbot::get_all_values_in "link" "$yaml_file" | symlinks::fzf -m --preview "${preview_cmd[*]}" --header "Select dotfile(s) to edit the link."))
+  [[ -z "${new_origin_link_path:-}" ]] && output::question_default "Write the new link for '$origin_link_path'" "$origin_link_path" "new_origin_link_path"
+  [[ "$origin_link_path" == "$new_origin_link_path" ]] && output::error "Skipping, nothing to change." && exit 1
 
-  for df in "${dotfiles[@]}"; do
-    links+=("$(dotbot::get_key_by_value_in "link" "$df" "$yaml_file")")
+  symlinks::edit_link_by_link_path "$yaml_file" "$origin_link_path" "$new_origin_link_path"
+
+  if $?; then
+    output::error "Link could not be edited"
+    exit 1
+  else
+    output::solution "Link '$origin_link_path' changed to '$new_origin_link_path' for file: $yaml_link_value"
+  fi
+else
+  links=("${origin_link_path:-}")
+  new_links=("${new_origin_link_path:-}")
+
+  preview_cmd='. "$DOTLY_PATH/scripts/core/_main.sh";'
+  preview_cmd+='dot::get_script_src_path "dotbot_yaml_edit.sh";'
+  preview_cmd+="yaml_file=$yaml_file;"
+  preview_cmd+='echo "Press Tab+Shift to select multiple options.\n'
+  preview_cmd+='Press Ctrl+C to exit with no selection.\n\n'
+  preview_cmd+='----\n\nLinks:\n\n'
+  preview_cmd+='$(cat "$yaml_file" | dotbot::jq_yaml_file -r ".[].link | values")";'
+
+  if [ -z "${links[*]}" ] && $by_value; then
+    dotfiles=($(dotbot::get_all_values_in "link" "$yaml_file" | symlinks::fzf -m --preview "${preview_cmd[*]}" --header "Select dotfile(s) to edit the link."))
+
+    for df in "${dotfiles[@]}"; do
+      links+=("$(dotbot::get_key_by_value_in "link" "$df" "$yaml_file")")
+    done
+  elif [ -z "${links[*]}" ]; then
+    links=($(dotbot::get_all_keys_in "link" "$yaml_file" | symlinks::fzf -m --preview "${preview_cmd[*]}" --header "Select link(s) to edit the link."))
+  fi
+
+  for current_link in "${links[@]}"; do
+    yaml_link_value="$(dotbot::get_value_of_key_in "link" "$current_link" "$yaml_file")"
+
+    output::question_default "Write the new link for '$current_link'" "$current_link" "new_link"
+
+    [[ -n "$new_link" ]] && [[ "$new_link" != "$current_link" ]] && {  
+      symlinks::edit_link_by_link_path "$yaml_file" "$current_link" "$new_link"
+
+      if $?; then
+        output::error "Link '$current_link' could not be updated to '$new_link'"
+        exit 1
+      else
+        output::solution "Link '$current_link' changed to '$new_link' for file: $yaml_link_value"
+      fi
+    }
   done
-elif [ -z "${links[*]}" ]; then
-  links=($(dotbot::get_all_keys_in "link" "$yaml_file" | symlinks::fzf -m --preview "${preview_cmd[*]}" --header "Select link(s) to edit the link."))
 fi
 
-for l in "${links[@]}"; do
-  dofile_path="" dotfile_path="$(dotbot::get_value_of_key_in "link" "$l" "$yaml_file")"
-
-  output::question_default "Write the new link for '$l'" "$l" "new_link"
-
-  [[ -n "$new_link" ]] && [[ "$new_link" != "$l" ]] && {  
-    echo "dotbot::add_or_edit_json_value_to_directive link $new_link $dotfile_path $yaml_file"
-    #dotbot::add_or_edit_json_value_to_directive "link" "$new_link" "$dotfile_path" "$yaml_file"
-    output::solution "Link '$l' changed to '$new_link' for file: $dotfile_path"
-  }
-done
-
-$no && exit 0
+$no &&  exit 0
 
 if ${yes:-}; then
   "$DOTLY_PATH/bin/dot" symlinks apply
