[Fix] shellcheck and linter (#29)
* Fixed templates to include also DOTLY_PATH. Now can pass a shellcheck analysis

* Fixed shellcheck errors with arrays

* Fixed shellcheck errors with pipes

* Fixed shellcheck critical errors

* Fixed shellcheck minor errors

* Added a way to apply patched directly in the linter

* Fixed linter to apply patches and avoid zsh errors

* Applied linter patches

* Resolved some linting errors manually in async.sh library

Co-authored-by: Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>

diff --git a/scripts/package/brew b/scripts/package/brew
--- a/scripts/package/brew
+++ b/scripts/package/brew
@@ -1,5 +1,6 @@
 #!/usr/bin/env bash
 
+#shellcheck disable=1091
 . "$DOTLY_PATH/scripts/core/_main.sh"
 dot::load_library "dump.sh" "package"
 
@@ -25,32 +26,32 @@ case $1 in
   brew leaves
   ;;
 "cleanup")
-    BREW_PATH="${BREW_PATH:-$DOTFILES_PATH/os/mac/brew}"
-    HOMEBREW_DUMP_FILE_PATH="${optional_path_brewfile:-$(package::exists_dump_current_machine_file "$BREW_PATH")}"
-    
-    if ! ${never_prompt:-false}; then
-      [[ -z "$HOMEBREW_DUMP_FILE_PATH" ]] || ${prompt:-false} && package::which_file "$BREW_PATH" "Select Brewfile to import" "HOMEBREW_DUMP_FILE_PATH"
-    fi
+  BREW_PATH="${BREW_PATH:-$DOTFILES_PATH/os/mac/brew}"
+  HOMEBREW_DUMP_FILE_PATH="${optional_path_brewfile:-$(package::exists_dump_current_machine_file "$BREW_PATH")}"
 
-    if [[ -f $HOMEBREW_DUMP_FILE_PATH ]]; then
-      cleanup_cmd="$(which brew) bundle --file=\"${HOMEBREW_DUMP_FILE_PATH}\" --force cleanup"
-      output::write "This will execute the command... "
-      output::write "    $cleanup_cmd"
+  if ! ${never_prompt:-false}; then
+    [[ -z "$HOMEBREW_DUMP_FILE_PATH" ]] || ${prompt:-false} && package::which_file "$BREW_PATH" "Select Brewfile to import" "HOMEBREW_DUMP_FILE_PATH"
+  fi
 
-      if output::yesno "Still want to perform the action"; then
-        $(which brew) bundle --file="${HOMEBREW_DUMP_FILE_PATH}" --force cleanup
-        output::solution "Cleanup performed, your system only have the Brewfile packages"
-      else
-        output::error "User aborted"
-        exit 1
-      fi
+  if [[ -f $HOMEBREW_DUMP_FILE_PATH ]]; then
+    cleanup_cmd="$(which brew) bundle --file=\"${HOMEBREW_DUMP_FILE_PATH}\" --force cleanup"
+    output::write "This will execute the command... "
+    output::write "    $cleanup_cmd"
 
-      if output::yesno "Do you want to execute additional 'brew cleanup'"; then
-        $(which brew) cleanup
-      fi
+    if output::yesno "Still want to perform the action"; then
+      $(which brew) bundle --file="${HOMEBREW_DUMP_FILE_PATH}" --force cleanup
+      output::solution "Cleanup performed, your system only have the Brewfile packages"
     else
-      output::error "No Brewfile found"
+      output::error "User aborted"
+      exit 1
     fi
+
+    if output::yesno "Do you want to execute additional 'brew cleanup'"; then
+      $(which brew) cleanup
+    fi
+  else
+    output::error "No Brewfile found"
+  fi
   ;;
 *)
   exit 1
diff --git a/scripts/script/create b/scripts/script/create
--- a/scripts/script/create
+++ b/scripts/script/create
@@ -4,12 +4,12 @@ set -euo pipefail
 
 [[ -z "$DOTLY_PATH" ]] && exit 1
 
-#shellcheck source=/dev/null
+#shellcheck disable=SC1091
 . "$DOTLY_PATH/scripts/core/_main.sh"
 dot::load_library "templating.sh"
 
 ##? Dotly script creator
-##? 
+##?
 ##?
 ##? Usage:
 ##?   create [-h | --help]
@@ -46,107 +46,106 @@ if ${version:-}; then
 fi
 
 case "${1:-}" in
-  "bin")
-    new_script_path="$DOTFILES_PATH/bin/${name:-}"
-    if [[ -z "${name:-}" ]]; then
-      output::error "🚨 No name for the script provided"
-      exit 1
-    fi
+"bin")
+  new_script_path="$DOTFILES_PATH/bin/${name:-}"
+  if [[ -z "${name:-}" ]]; then
+    output::error "🚨 No name for the script provided"
+    exit 1
+  fi
 
-    if [[ ! -d "$DOTFILES_PATH" ]]; then
-      output::error "❌ Your dotfiles could not be found"
-      exit 1
-    fi
-    mkdir -p "$DOTFILES_PATH/bin"
+  if [[ ! -d "$DOTFILES_PATH" ]]; then
+    output::error "❌ Your dotfiles could not be found"
+    exit 1
+  fi
+  mkdir -p "$DOTFILES_PATH/bin"
 
-    if [[ -f "$new_script_path" ]] &&\
-        ! output::yesno " ⚠️ Script \`${name:-}\` exists in \`\$DOTFILES_PATH/bin\`! Do you want to overwrite it (this will delete current file)"
-    then
-      output::error "User aborted"
-      exit 1
-    fi
+  if [[ -f "$new_script_path" ]] &&
+    ! output::yesno " ⚠️ Script \`${name:-}\` exists in \`\$DOTFILES_PATH/bin\`! Do you want to overwrite it (this will delete current file)"; then
+    output::error "User aborted"
+    exit 1
+  fi
 
-    rm -f "$new_script_path"
-    touch "$new_script_path"
-    printf "#!/usr/bin/env bash\n\n" >> "$new_script_path"
-    printf "set -euo pipefail\n" >> "$new_script_path"
-    #shellcheck disable=SC2016
-    printf '. "$DOTLY_PATH/scripts/core/_main.sh"\n' >> "$new_script_path"
+  rm -f "$new_script_path"
+  touch "$new_script_path"
+  printf "#!/usr/bin/env bash\n\n" >>"$new_script_path"
+  printf "set -euo pipefail\n" >>"$new_script_path"
+  #shellcheck disable=SC2016
+  printf '. "$DOTLY_PATH/scripts/core/_main.sh"\n' >>"$new_script_path"
 
-    chmod u+x "$new_script_path"
+  chmod u+x "$new_script_path"
 
+  output::empty_line
+  output::solution "The script \`$name\` where successfully created."
+  output::write ""
+  output::write "You can access the scipt with your favorite editor by executing:"
+  output::write "\$EDITOR \"\$DOTFILES_PATH/bin/${name:-}\""
+  output::empty_line
+
+  ;;
+*)
+  if [[ -z "${context:-}" ]] || [[ -z "${script_name:-}" ]]; then
+    output::error "You should provide a context and script name"
+    output::write "Use: $0 -h"
+    exit 1
+  fi
+
+  SCRIPT_TEMPLATE_PATH="$(dot::get_script_path)/src/templates/script"
+
+  # Path variables
+  if ${core:-}; then
     output::empty_line
-    output::solution "The script \`$name\` where successfully created."
-    output::write ""
-    output::write "You can access the scipt with your favorite editor by executing:"
-    output::write "\$EDITOR \"\$DOTFILES_PATH/bin/${name:-}\""
+    output::write "\033[0;31m\033[1m  ALERT!!!!!"
+    output::write "Create this script in your DOTLY scripts folder could be very dangerous."
+    output::write "This is an option thinked only for DOTLY devs.\033[0m"
     output::empty_line
+    output::yesno "Are you sure you still want to coninue" "N" || { output::answer "User aborted" && exit 1; }
 
-    ;;
-  *)
-    if [[ -z "${context:-}" ]] || [[ -z "${script_name:-}" ]]; then
-      output::error "You should provide a context and script name"
-      output::write "Use: $0 -h"
-      exit 1
-    fi
+    script_path="$DOTLY_PATH/scripts/$context"
+  else
+    script_path="$DOTFILES_PATH/scripts/$context"
+  fi
 
-    SCRIPT_TEMPLATE_PATH="$(dot::get_script_path)/src/templates/script"
+  script_filepath="$script_path/$script_name"
 
-    # Path variables
-    if ${core:-}; then
-      output::empty_line
-      output::write "\033[0;31m\033[1m  ALERT!!!!!"
-      output::write "Create this script in your DOTLY scripts folder could be very dangerous."
-      output::write "This is an option thinked only for DOTLY devs.\033[0m"
-      output::empty_line
-      output::yesno "Are you sure you still want to coninue" "N" || { output::answer "User aborted" && exit 1; }
+  # Which template to use
+  if ${sample:-}; then
+    SCRIPT_TEMPLATE_PATH="${SCRIPT_TEMPLATE_PATH}-more"
+  fi
 
-      script_path="$DOTLY_PATH/scripts/$context"
-    else
-      script_path="$DOTFILES_PATH/scripts/$context"
-    fi
+  # Create the script context (folder)
+  mkdir -p "$script_path"
 
-    script_filepath="$script_path/$script_name"
+  if [[ -d "$DOTFILES_PATH/scripts/$context" ]]; then
+    output::solution "$script_path were created or exists previously"
+  fi
 
-    # Which template to use
-    if ${sample:-}; then
-      SCRIPT_TEMPLATE_PATH="${SCRIPT_TEMPLATE_PATH}-more"
-    fi
-
-    # Create the script context (folder)
-    mkdir -p "$script_path"
-
-    if [[ -d "$DOTFILES_PATH/scripts/$context" ]]; then
-      output::solution "$script_path were created or exists previously"
-    fi
-
-    # If script exits ask user to overwrite
-    if [[ -f $script_filepath ]]; then
-      output::yesno "The script exists, do you want to delete it and create a empty script" "N" ||\
-        {
-          output::error "The script name \"$script_name\" exists in context \"$context\" and user refuse to recreate the script" &&\
-          output::write "Provide a different name for the script or context." &&\
+  # If script exits ask user to overwrite
+  if [[ -f $script_filepath ]]; then
+    output::yesno "The script exists, do you want to delete it and create a empty script" "N" ||
+      {
+        output::error "The script name \"$script_name\" exists in context \"$context\" and user refuse to recreate the script" &&
+          output::write "Provide a different name for the script or context." &&
           exit 1
-        }
-    fi
+      }
+  fi
 
-    # Variables for the script
-    author="${author:-$(git config --global --get user.name)}"
-    email="${email:-$(git config --global --get user.email)}"
-    description="${script_description[*]:-}"
+  # Variables for the script
+  author="${author:-$(git config --global --get user.name)}"
+  email="${email:-$(git config --global --get user.email)}"
+  description="${script_description[*]:-}"
 
-    # Description can not be empty
-    [[ -z "$description" ]] && output::question "Description can not be empty, describe your script" "description"
+  # Description can not be empty
+  [[ -z "$description" ]] && output::question "Description can not be empty, describe your script" "description"
 
-    cp "${SCRIPT_TEMPLATE_PATH}" "$script_filepath"
-    templating::replace "$script_filepath" --script-name="$script_name" --script-context="$context" --script-author="$author" --script-author-email="$email" --script-description="$description" > /dev/null
-    chmod u+x "$script_filepath"
+  cp "${SCRIPT_TEMPLATE_PATH}" "$script_filepath"
+  templating::replace "$script_filepath" --script-name="$script_name" --script-context="$context" --script-author="$author" --script-author-email="$email" --script-description="$description" >/dev/null
+  chmod u+x "$script_filepath"
 
-    output::empty_line
-    output::solution "The script '$script_name' where successfully created."
-    output::write ""
-    output::write "You can access the scipt with your favorite editor by executing:"
-    output::write "\$EDITOR \"\$DOTFILES_PATH/scripts/$context/$script_name\""
-    output::empty_line
-    ;;
+  output::empty_line
+  output::solution "The script '$script_name' where successfully created."
+  output::write ""
+  output::write "You can access the scipt with your favorite editor by executing:"
+  output::write "\$EDITOR \"\$DOTFILES_PATH/scripts/$context/$script_name\""
+  output::empty_line
+  ;;
 esac
