Fist stable version of DOTLY marketplace

diff --git a/scripts/dotly/install b/scripts/dotly/install
--- a/scripts/dotly/install
+++ b/scripts/dotly/install
@@ -3,6 +3,9 @@
 [[ -z "$DOTLY_PATH" ]] && exit 1
 
 . "$DOTLY_PATH/scripts/core/_main.sh"
+. "$DOTLY_PATH/scripts/dotly/tools/github.sh"
+
+[ -z "$DOTFILES_SCRIPTS_PATH" ] && output::error "Failed to load needed GitHub library" && exit
 
 ##? Install script from dotly marketplace
 ##? 
@@ -10,7 +13,7 @@
 ##? Usage:
 ##?   install [-h | --help]
 ##?   install [-v | --version]
-##?   install [-y | --yes] <context> <script>
+##?   install [-y | --yes] <context> [<script>]
 ##?
 ##? Options:
 ##?   -h --help     Show this help
@@ -31,11 +34,55 @@ if ${version:-}; then
   exit
 fi
 
-# Here begin your script
+# Begin with empty line
+output::empty_line
 
-case $1 in
-# Any subcommand should be here
-*)
-  exit 1
-  ;;
-esac
+if github::check_cache_folder_should_be_created; then
+  output::error "There is no cache to install scripts."
+  output::answer "It can be updated and created asynchronously by executing 'dot self init marketplace'"
+  output::yesno "Do you want to create synchonously (it could take some time)" && "$DOTLY_PATH/bin/dot" dotly cache --force
+fi
+
+install="$context"
+! github::check_remote_exists "$context" "${script:-}" && output::error "Script or context could not be found" && exit
+
+# Check if it is installed
+if [[ -n "$script" ]]; then
+  install="$context/$script"
+
+  if [[ -f "$DOTFILES_SCRIPTS_PATH/$context/$script" ]] && ! $yes; then
+    output::error "ATTENTION! THIS IS IMPORTANT!"
+    output::empty_line
+    output::write "The script you are trying to install exists in your dotfiles scripts. If you"
+    output::write "continue this installation, will overwrite the script in your context with the"
+    output::write "same name as the one you are trying to install."
+    output::empty_line
+    output::write "PLEASE, MAKE SURE ABOUT WHAT YOU ARE DOING, ANY LOSING OF DATA WILL BE YOUR"
+    output::write "RESPONSABILITY."
+    output::empty_line
+    output::yesno "Sure you want to continue?" || exit
+    output::empty_line
+  fi
+elif [[ -d "$DOTFILES_SCRIPTS_PATH/$context" ]] && ! $yes; then
+  output::empty_line
+  output::error "ATTENTION! THIS IS IMPORTANT!"
+  output::write "The context \"$context\" exists in your dotfiles scripts. If you continue"
+  output::write "this installation will overwrite the scripts in your context with the"
+  output::write "same name as the remote files. This is the unique way to update but could"
+  output::write "be also a way to lost any current existing custom script in this context."
+  output::empty_line
+  output::write "PLEASE, MAKE SURE ABOUT WHAT YOU ARE DOING, ANY LOSING OF DATA WILL BE YOUR"
+  output::write "RESPONSABILITY."
+  output::empty_line
+  output::yesno "Sure you want to continue?" || exit
+  output::empty_line
+fi
+
+if github::install_from_search "$install"; then
+  output::solution "Installed, now you can use it with dot command"
+else
+  output::error "Could not be installed. Please try installing from the search with:"
+  output::error "dot dotly search ${script:-$context}"
+fi
+
+output::empty_line
