style: use tabs to indent (#225)

diff --git a/scripts/self/install b/scripts/self/install
--- a/scripts/self/install
+++ b/scripts/self/install
@@ -7,8 +7,8 @@ export ZIM_HOME="$DOTFILES_PATH/shell/zsh/.zim"
 export PATH="$HOME/.cargo/bin:$PATH"
 
 if platform::is_macos; then
-  output::answer "🍎 Setting up macOS platform"
-  install_macos_custom
+	output::answer "🍎 Setting up macOS platform"
+	install_macos_custom
 fi
 
 script::depends_on docpars fzf zsh python
@@ -30,8 +30,8 @@ output::answer "Setting up symlinks"
 touch "$HOME/.z"
 
 if ! str::contains zsh "$SHELL"; then
-  output::answer "Setting zsh as the default shell"
-  sudo chsh -s "$(command -v zsh)" | log::file "Setting zsh as default shell"
+	output::answer "Setting zsh as the default shell"
+	sudo chsh -s "$(command -v zsh)" | log::file "Setting zsh as default shell"
 fi
 
 output::answer "Installing Zim"
@@ -43,11 +43,11 @@ output::answer "Installing completions"
 output::answer "Executing custom restoration scripts"
 install_scripts_path="$DOTFILES_PATH/restoration_scripts"
 if [ -d "$install_scripts_path" ]; then
-  find "$install_scripts_path" -mindepth 1 -maxdepth 1 -type l,f -name '*.sh' |
-    sort |
-    while read -r install_script; do
-      { [[ -x $install_script ]] && . "$install_script" | log::file "Executing afterinstall: $(basename "$install_script")"; } || {
-        output::error "Install script error in $(basename "$install_script")"
-      }
-    done
+	find "$install_scripts_path" -mindepth 1 -maxdepth 1 -type l,f -name '*.sh' |
+		sort |
+		while read -r install_script; do
+			{ [[ -x $install_script ]] && . "$install_script" | log::file "Executing afterinstall: $(basename "$install_script")"; } || {
+				output::error "Install script error in $(basename "$install_script")"
+			}
+		done
 fi
