Improve installation output

diff --git a/scripts/self/install b/scripts/self/install
--- a/scripts/self/install
+++ b/scripts/self/install
@@ -8,23 +8,19 @@ source "$DOTLY_PATH/scripts/self/utils/install.sh"
 export ZIM_HOME="$DOTLY_PATH/modules/zimfw"
 
 installer::install_zsh() {
-  output::error "Zsh not installed, installing"
+  output::error "zsh not installed, installing"
 
-  if "$DOTLY_PATH/bin/dot" package install zsh 2>&1; then
-    output::solution "Zsh installed!"
-  else
-    output::error "Could not install Zsh!"
+  if ! "$DOTLY_PATH/bin/dot" package install zsh >/dev/null 2>&1; then
+    output::error "Could not install zsh!"
     exit 5
   fi
 }
 
 installer::install_fzf() {
-  output::error "Fzf not installed, installing"
+  output::error "fzf not installed, installing"
 
-  if $DOTLY_PATH/bin/dot package install fzf 2>&1; then
-    output::solution "fzf installed!"
-  else
-    output::error "Could not install Fzf!"
+  if ! $DOTLY_PATH/bin/dot package install fzf >/dev/null 2>&1; then
+    output::error "Could not install fzf!"
     exit 5
   fi
 }
@@ -47,25 +43,16 @@ fi
 
 # @todo Backup if exists before
 output::answer "Setting up symlinks"
-"$DOTLY_PATH/bin/dot" symlinks apply 2>&1
+"$DOTLY_PATH/bin/dot" symlinks apply >/dev/null 2>&1
 
-if ! platform::command_exists zsh; then
-  installer::install_zsh
-else
-  output::answer "Zsh already installed!"
-fi
+! platform::command_exists zsh && installer::install_zsh
 
 if ! str::contains zsh "$SHELL"; then
-  output::answer "Setting Zsh as the default shell (you'll have to logout and login to see the changes)"
-  sudo chsh -s "$(command -v zsh)"
+  output::answer "Setting zsh as the default shell"
+  sudo chsh -s "$(command -v zsh)" >/dev/null 2>&1
 fi
 
-if ! platform::command_exists fzf; then
-  installer::install_fzf
-else
-  output::answer "Fzf already installed!"
-fi
+! platform::command_exists fzf && installer::install_fzf
 
-output::answer "Installing Zim"
-
-zsh "$ZIM_HOME/zimfw.zsh" install
+output::answer "Installing zim"
+zsh "$ZIM_HOME/zimfw.zsh" install >/dev/null 2>&1
