Added a way to execute user scripts in installation process

diff --git a/scripts/self/install b/scripts/self/install
--- a/scripts/self/install
+++ b/scripts/self/install
@@ -75,3 +75,14 @@ zsh "$ZIM_HOME/zimfw.zsh" install | log::file "Installing zim"
 output::answer "Installing completions"
 "$DOTLY_PATH/bin/dot" shell zsh reload_completions
 
+output::answer "Executing self install scripts for custom installings"
+install_scripts_path="$DOTFILES_PATH/self-install-scripts"
+if [ -d "$install_scripts_path" ]; then
+  find "$install_scripts_path" -mindepth 1 -maxdepth 1 -type l,f -name '*.sh' |\
+    sort |\
+    while read -r install_script; do
+      { [[ -x "$install_script" ]] && . "$install_script" | log::file "Executing afterinstall: $(basename "$install_script")"; } || {
+        output::error "Install script error in $(basename "$install_script")"
+      }
+    done
+fi
