Added all features for this branch - Added core functions in output.sh: output::question_default, output::yesno - Fixed in core functions output.sh: output::question. This was adding a new line to the prompt that creates confusion. - Added export/import packages of package managers by given alias or hostname. - Added export/import mac defaults by given alias or hostname.

diff --git a/scripts/mac/brew b/scripts/mac/brew
--- a/scripts/mac/brew
+++ b/scripts/mac/brew
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 
 source "$DOTLY_PATH/scripts/core/_main.sh"
+source "$DOTLY_PATH/scripts/package/utils/dump.sh"
 
 ##? Some brew utils.
 ##?   - If cleanup does not receive any param will take your
@@ -9,7 +10,14 @@ source "$DOTLY_PATH/scripts/core/_main.sh"
 ##?
 ##? Usage:
 ##?   brew list_installed
-##?   brew cleanup [<optional_path_brewfile>]
+##?   brew cleanup [--prompt|-p|--never-prompt|-n] [<optional_path_brewfile>]
+##?
+##? Options:
+##?   --prompt -p        You will be asked always for a file to restore in every package manager or lang
+##?   --never-prompt -n  You will never be asked for any file to restore, if there is no file with the
+##?                      same name as current hostname the package/lang is ignored and continue to try
+##?                      with next package
+##?
 docs::parse "$@"
 
 case $1 in
@@ -17,15 +25,29 @@ case $1 in
   brew leaves
   ;;
 "cleanup")
-    HOMEBREW_DUMP_FILE_PATH=${optional_path_brewfile:-"$DOTFILES_PATH/os/mac/brew/Brewfile"}
-    cleanup_cmd="$(which brew) bundle --file=\"${HOMEBREW_DUMP_FILE_PATH}\" --force cleanup"
-    output::write "This will execute the command... "
-    output::write "    $cleanup_cmd"
+    BREW_PATH="${BREW_PATH:-$DOTFILES_PATH/os/mac/brew}"
+    HOMEBREW_DUMP_FILE_PATH="${optional_path_brewfile:-$(package::exists_dump_current_machine_file "$BREW_PATH")}"
+    
+    if ! ${never_prompt:-false}; then
+      [[ -z "$HOMEBREW_DUMP_FILE_PATH" ]] || ${prompt:-false} && package::which_file "$BREW_PATH" "Select Brewfile to import" "HOMEBREW_DUMP_FILE_PATH"
+    fi
+
     if [[ -f $HOMEBREW_DUMP_FILE_PATH ]]; then
-      output::question "Still want to perform the action?" confirm_action
-      $(which brew) bundle --file="${HOMEBREW_DUMP_FILE_PATH}" --force cleanup
-      output::question "Do you want to execute additional 'brew cleanup'" brew_cleanup
-      [[ ! -z $brew_cleanup ]] && $(which brew) cleanup
+      cleanup_cmd="$(which brew) bundle --file=\"${HOMEBREW_DUMP_FILE_PATH}\" --force cleanup"
+      output::write "This will execute the command... "
+      output::write "    $cleanup_cmd"
+
+      if output::yesno "Still want to perform the action"; then
+        $(which brew) bundle --file="${HOMEBREW_DUMP_FILE_PATH}" --force cleanup
+        output::solution "Cleanup performed, your system only have the Brewfile packages"
+      else
+        output::error "User aborted"
+        exit 1
+      fi
+
+      if output::yesno "Do you want to execute additional 'brew cleanup'"; then
+        $(which brew) cleanup
+      fi
     else
       output::error "No Brewfile found"
     fi
