Refactored library to multiple files because it is easier to understand

diff --git a/scripts/secrets/init b/scripts/secrets/init
--- a/scripts/secrets/init
+++ b/scripts/secrets/init
@@ -3,7 +3,11 @@
 [[ -z "$DOTLY_PATH" ]] && exit 1
 
 . "$DOTLY_PATH/scripts/core/_main.sh"
-. "$DOTLY_PATH/scripts/secrets/lib/secrets.sh" # Included only to install yq if is not installed
+. "$DOTLY_PATH/scripts/secrets/lib/install_needed_soft_and_vars.sh"
+
+secrets::check_remote_repository_exists() {
+  git ls-remote "$1" >/dev/null 2>&1
+}
 
 ##? Initialize a secrets repository. Private repository to store your secrets.
 ##?  - Without the url it will start the repository locally with 'secrets' as
@@ -12,10 +16,12 @@
 ##?    and add that url to remote origin.
 ##?  The repository is initilized as git submodule in $DOTLY_SECRETS_MODULES_PATH.
 ##?
+##?         ⚠️ IT IS RECOMMENDED TO USE SSH GIT URLS ⚠️
+##?
 ##? Usage:
 ##?   init [-h | --help]
 ##?   init [-v | --version]
-##?   init [-r | --recreate] <git_repository_url> [<branch>]
+##?   init [-r | --recreate] <git_repository_ssh_url> [<branch>]
 ##?   
 ##?
 ##? Options:
@@ -35,6 +41,12 @@ SCRIPT_VERSION="1.0.0"
 if ${version:-}; then
   output::write "$SCRIPT_NAME v$SCRIPT_VERSION"
   exit
+fi
+
+if ! secrets::check_remote_repository_exists "$git_repository_ssh_url"; then
+  output::empty_line
+  output::error "🚨 The given git url does not exists or could not get access to."
+  output::empty_line
 fi
 
 start_path="$(pwd)"
@@ -68,7 +80,7 @@ if $recreate && [[ -d "$DOTLY_SECRETS_MODULE_PATH" ]] ; then
   output::empty_line
 fi
 
-git submodule add -b "${branch:-master}" "$git_repository_url" "$DOTLY_SECRETS_MODULE_PATH"
+git submodule add -b "${branch:-master}" "$git_repository_ssh_url" "$DOTLY_SECRETS_MODULE_PATH"
 
 "$DOTLY_PATH/bin/dot" secrets apply
 
