Added a warning because executing this command without knowledge could be best ever EPIC fail

diff --git a/scripts/secrets/purge b/scripts/secrets/purge
--- a/scripts/secrets/purge
+++ b/scripts/secrets/purge
@@ -26,11 +26,13 @@ purge_vars() {
 ##? Usage:
 ##?   purge [-h | --help]
 ##?   purge [-v | --version]
-##?   purge [files|vars] [-n | --no-sync]
+##?   purge [files|vars] [-n | --no-sync] [-f | --force]
 ##?
 ##? Options:
 ##?   -h --help     Show this help
 ##?   -v --version  Show the program version
+##?   -f --force    No question about if you are sure... Use this option only if
+##?                 you are brave enough
 ##?   -n --no-sync  Do not sync changes
 ##?
 ##? Author:
@@ -47,7 +49,25 @@ if ${version:-}; then
   exit
 fi
 
+output::empty_line
+output::error "WARNING"
+output::empty_line
+output::error "This could be dangerous you will delete without the possibility of restoration."
+output::error "It is recommended to use --no-sync option and later when you are sure you do"
+output::error "not want your files do the sync manually."
+output::empty_line
+
+if ! $force; then
+  output::yesno "Do you still want to continue" "N" || {
+    output::error "User aborted"
+    exit 1
+  }
+  
+  output::empty_line
+fi
+
 output::header "🗑 Purging"
+
 case "$1"; in
 "vars")
   purge_vars
