Remove files from store

diff --git a/scripts/secrets/store b/scripts/secrets/store
--- a/scripts/secrets/store
+++ b/scripts/secrets/store
@@ -13,26 +13,15 @@
 ##?   store [-v | --version]
 ##?   store [-p | --prompt] [-n | --no-sync]  <item_path> [<secrets_subfolder>]
 ##?   store edit [-n | --no-sync] [<item_path> [<new_symlink_path>]] 
-##?   store edit [<secret_path>]
-##?   store delete [<secret_path>] 
-##?   store purge 
+##?   store edit [-n | --no-sync] [<secret_path>]
+##?   store delete [-n | --no-sync] [<secret_path>]
+##?   store purge [-n | --no-sync]
 ##?
 ##? Options:
 ##?   -h --help     Show this help
 ##?   -v --version  Show the program version
 ##?   -p --prompt   Ask subfolder path to store the file
 ##?   -n --no-sync  Do not sync changes
-##?   --message     Change default sync message to defined message
-##?   edit          Edit a secret providing the relative path to
-##?                 `$DOTFILES_PATH/modules/secrets/files` if you do
-##?                 not provide any it will show a output with fzf to
-##?                 select the file(s) you want to edit.
-##?   delete        Delete a secret providing the relative path to
-##?                 `$DOTFILES_PATH/modules/secrets/files` if you do
-##?                 not provide any it will show a output with fzf to
-##?                 select the file(s) you want to delete.
-##?   purge         Delete all stored secrets in
-##?                    `$DOTFILES_PATH/modules/secrets/files`
 ##?
 ##? Author:
 ##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
@@ -50,7 +39,23 @@ fi
 
 case $1 in
 "delete")
-  echo "Not implemented"
+  # Provided file
+  if [[ -n "${2:-}" ]]; then
+    file_secret_path="$(secrets::check_exists "files/$2")"
+    if [[ -z $file_secret_path ]]; then
+      output::error "🗃 Eror 404: File not found"
+      exit 1
+    fi
+
+    secrets::remove_symlink_by_stored_file "$2"
+    exit 0
+  fi
+
+  # Not provided file
+  deleted_items=($(secrets::find --exclude files | secrets::fzf "Select file(s) to be deleted"))
+  for item in "${deleted_items[@]}"; do
+    secrets::remove_symlink_by_stored_file "$item"
+  done
   ;;
 "edit")
   echo "Not implemented"
