Added a warning before sync. And also added an option to avoid the warnign.

diff --git a/scripts/secrets/sync b/scripts/secrets/sync
--- a/scripts/secrets/sync
+++ b/scripts/secrets/sync
@@ -11,12 +11,13 @@
 ##? Usage:
 ##?   sync [-h | --help]
 ##?   sync [-v | --version]
-##?   sync [-n | --no-apply]
+##?   sync [-n | --no-apply] [-y | --yes]
 ##?
 ##? Options:
 ##?   -h --help      Show this help
 ##?   -v --version   Show the program version
 ##?   -n --no-apply  Not apply symlinks
+##?   -y --yes       Not prompt if you are sure about you will want to do
 ##?
 ##? Author:
 ##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
@@ -44,6 +45,25 @@ cd "$DOTFILES_PATH/$DOTLY_SECRETS_MODULE_PATH" || {
 }
 
 output::header "Syncronizing your secrets"
+
+if ! $yes; then
+  output::empty_line
+  output::error "🚨🚨🚨🚨 WARNING! 🚨🚨🚨🚨"
+  output::empty_line
+  output::write "Syncronize your secrets could delete some files. If you have deleted those"
+  output::write "files across the commits and you do not have a backup in any other safe"
+  output::write "place, you can lost your files forever."
+  output::write "- 😱 Forever? 😥 🙀 😰"
+  output::write "- 😥 Yes."
+  output::write "- 🙀 Nothing is deleted forever."
+  output::write "- 😰 Well, I am just a dev. Decision is up to you."
+  output::empty_line
+  output::yesno "Are you sure you want to continue" || {
+    output::error "User aborted"
+    exit 1
+  }
+  output::empty_line
+fi
 
 {
   git add . >/dev/null 2>&1 &&\
